### ISSUE TITLE
quest locations in middle of ocean

### ISSUE THREAD

**Issue by Reforged-Network** [Toma1O6/Guns-RPG#19]
I'm not sure if this is intended but I have encountered a couple instances where the area quests will bring you to the middle of an ocean to kill mobs.
So far I've had this happen with Bone Crusher I and Arachnophobia I.

**Comment by Toma1O6** [comment]
Hi, this situation can definitely happen. By design, it tries to select position which is not in water biome category (rivers, oceans), but if that fails then it just picks some completely random location which may be in the middle of the ocean.
This mostly depends on how the world is generated, if there's nothing but oceans around your village then the quest areas will be always in oceans.
