### ISSUE TITLE
How to use command "/gunsrpg progression gunsrpg:weapon" ?

### ISSUE THREAD

**Issue by Frenqy** [Toma1O6/Guns-RPG#22]

**Comment by Toma1O6** [comment]
it works exactly the same way as using `gunsrpg:level` selector. But since it targets specific weapon, you need to provide the weapon id as last parameter, so for example when you want to increase level on AUG, you would use `/gunsrpg progression gunsrpg:weapon level 1 "gunsrpg:awm"` and it would add +1 levels to the weapon skill tree.

If you have any extra questions about this, you can contact us directly on our [Discord server](https://discord.gg/WEFYxwS8E3)
